---
- hosts: web_servers
  become: yes  # Run tasks as root
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx web server
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes